---
# tasks file for launch_app

- name: Copy .env file to remote host
  copy:
    src: "{{ playbook_dir }}/.env"
    dest: /home/admin/.env
    mode: '0600'
- name: Run backend app container
  docker_container:
    name: my_app # Name of the container
    image: chengboss/tp-devops-simple-api # Backend API image
    env_file: /home/admin/.env
    pull : yes
    recreate : true
    networks:
      - name: my_network    # Connect container to the Docker network
      - name: my_network_front
        aliases:
          - spring-backend
