version: "3.9"

services:
  backend:
    image: spring-backend
    container_name: spring-backend
    networks:
      - app-network
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=pwd
    restart: unless-stopped

  database:
    image: my-postgres-db
    container_name: postgres-db
    networks:
      - app-network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  httpd:
    image: my-apache
    container_name: apache-web
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: