---
# tasks file for launch_database

- name: Copy .env file to remote host
  copy:
    src: "{{ playbook_dir }}/.env"
    dest: /home/admin/.env
    mode: '0600'
    
- name: Run Database container
  docker_container:
    name: my_db                      # Name of the container
    image: chengboss/tp-devops-db    # Docker image to use
    restart_policy: always  # 
    env_file: /home/admin/.env

    networks:                        # Connect container to the Docker network
      - name: my_network

