name: CI devops 2025
on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and test with Maven
        working-directory: ./TP1/backend/simpleapi
        run: mvn clean verify

      - name: SonarCloud analysis
        working-directory: ./TP1/backend/simpleapi
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=RyotaSh_TDTPDocker \
            -Dsonar.organization=ryotash \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: TP1/backend
          file: TP1/backend/Dockerfile
          push: true
          # Note: tags has to be all lower-case
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          # Build custom database image
          context: TP1
          file: TP1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-db

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          # Build httpd image
          context: TP1/HTTP
          file: TP1/HTTP/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key  
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts


      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Deploy application on remote server
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
        
